# Generated by Django 6.0.1 on 2026-02-22 17:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_project_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkUploadReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('upload_type', models.CharField(choices=[('PROJECT', 'Projects'), ('TASK', 'Tasks'), ('TIME_ENTRY', 'Time Entry')], max_length=20)),
                ('total_records', models.IntegerField(default=0)),
                ('success_records', models.IntegerField(default=0)),
                ('failed_records', models.IntegerField(default=0)),
                ('skipped_records', models.IntegerField(default=0)),
                ('file_name', models.CharField(blank=True, max_length=255, null=True)),
                ('error_summary', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.comment')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.task')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
