# Generated by Django 6.0.1 on 2026-02-22 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_bulkuploadreport_notification'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bulkuploadreport',
            options={},
        ),
        migrations.RemoveField(
            model_name='bulkuploadreport',
            name='error_summary',
        ),
        migrations.AddField(
            model_name='bulkuploadreport',
            name='failed_details',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='bulkuploadreport',
            name='skipped_details',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='bulkuploadreport',
            name='upload_type',
            field=models.CharField(choices=[('Projects', 'Project'), ('Tasks', 'Task'), ('Time-Entry', 'Time Entry')], max_length=30),
        ),
    ]
